version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3001:3000
    env_file:
      - .env
    restart: unless-stopped