version: '3.8'

services:

  api-service:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    image: server
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
